# Generated by Django 6.0 on 2025-12-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_usuariomodel_financamodel_usuarioforeng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financamodel',
            old_name='usuarioForeng',
            new_name='usuario',
        ),
    ]
